### ISSUE TITLE
Nightly publish job with slack notifications no longer runs

### ISSUE THREAD

**Issue by jerboaa** [adoptium/ci-jenkins-pipelines#258] opened 2022-03-02 10:05 UTC
We used to have a job which posted slack messages to the build channel, detailing whether or not latest nightly builds got published to github. This no longer works. I'm guessing due to https://github.com/adoptium/temurin-build/issues/2671

**Expected behaviour:**
Publish stats posted to build slack channel.

**Observed behaviour:**
No publish stats.

**Any other comments:**
https://github.com/adoptium/ci-jenkins-pipelines/blob/master/tools/nightly_build_and_test_stats.groovy#L35 and the like would probably need to get updated. It used to have `VARIANT=temurin` now it's `VARIANT=hotspot`

**Comment by jerboaa** [comment] 2022-03-02 10:08
Last successful run:
https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/569

It has this in the console output:
```
[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/569/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/569/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/569/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/569/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/569/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/569/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/569/console#)-------------- Nightly pipeline health report ------------------
[Pipeline] echo
===> JDK 8 nightly pipeline publish status: healthy. Last published: 2 day(s) ago
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: adoptium, channel: #build, color: good, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] echo
===> JDK 11 nightly pipeline publish status: healthy. Last published: 3 day(s) ago
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: adoptium, channel: #build, color: good, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] echo
===> JDK 17 nightly pipeline publish status: healthy. Last published: 3 day(s) ago
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: adoptium, channel: #build, color: good, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] echo
----------------------------------------------------------------
```

Most recent job doesn't:
https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/587/

**Comment by sxa** [comment] 2022-03-02 13:32
Hmmm [switching it back to hotspot ](https://github.com/sxa/ci-jenkins-pipelines/commit/9e8839c0a0242a7cc1f9b975b1da53fb2e6bd8b4)doesn't quite [have the desired effect](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/590/console) as we are not building a variant of "hotspot" any more so whever it's looking picks up the last builds from over two weeks ago, so we need to understand how to make it pick up the temurin data. I suspect we want to create a `nightlyBuildAndTestStats_temurin` variant which picks up the right thing, although if it's querying the information from TRSS then it might need some change to the logic there too?

I've left the job running from my branch just now until we resolve this.

**Comment by sxa** [comment] 2022-03-02 14:43
We resolved a problem with space issues on the TRSS server, although if it's still not showing the correct results today it's going to need some further investigation to understand whether the problem is TRSS not having the data available or whether the nightlyBuildAndTestStats_* jobs are not querying it properly for the temurin case.
FYI @smlambert @llxia @sophia-guo in case you have any insight/input today in @andrew-m-leonard 's absence.

**Comment by sophia-guo** [comment] 2022-03-02 17:19
Also update the job configuration with default VARIANT=temurin.

**Comment by sxa** [comment] 2022-03-02 17:25
@sophia-guo If I set the job to run from your `variant1` branch an set a VARIANT of `temurin` on the parameters, it is [still not retrieving the information](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/594/console) as far as I can see. Is there still an issue somewhere with TRSS that needs to be addressed?

**Comment by sophia-guo** [comment] 2022-03-02 17:45
The PR with variant1 branch is addressing no slack notifications issue. 

No information retrieved from TRSS is a different issue. There is no builds information ever since [Feb 16](https://trss.adoptium.net/) ( disk issue you mentioned before?).

**Comment by sophia-guo** [comment] 2022-03-02 17:47
Looks like it will only report recent 7 days infor.  https://github.com/adoptium/ci-jenkins-pipelines/pull/230. So no report data is expected.

**Comment by sophia-guo** [comment] 2022-03-02 18:02
Updated PR #259 Now should be fine https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/597/ with output

```
[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/597/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/597/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/597/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/597/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/597/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/597/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/597/console#)[Pipeline] echo
-------------- Nightly pipeline health report ------------------
[Pipeline] echo
===> JDK 8 nightly pipeline publish status: healthy. Last published: 15 day(s) ago
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: adoptium, channel: #build, color: good, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] echo
===> JDK 11 nightly pipeline publish status: healthy. Last published: 19 day(s) ago
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: adoptium, channel: #build, color: good, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] echo
===> JDK 17 nightly pipeline publish status: healthy. Last published: 19 day(s) ago
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: adoptium, channel: #build, color: good, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
```

**Comment by sxa** [comment] 2022-03-02 18:05
> Looks like it will only report recent 7 days infor. #230. So no report data is expected.
> There is no builds information ever since [Feb 16](https://trss.adoptium.net/) ( disk issue you mentioned before?).

That was resolved yesterday so I would expect it to show data from last night's pipelines unless there's another issue stopping it from being picked up - we had [JDK11 builds last night](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/) that were [successfully published as nightlies](https://github.com/adoptium/temurin11-binaries/releases/tag/jdk11u-2022-03-02-04-49-beta) so there's still an issue somewhere if they are not being picked up.

**Comment by jerboaa** [comment] 2022-03-02 20:03
Thanks for the fix folks!

**Comment by jerboaa** [comment] 2022-03-02 20:05
> > Looks like it will only report recent 7 days infor. #230. So no report data is expected.
> > There is no builds information ever since [Feb 16](https://trss.adoptium.net/) ( disk issue you mentioned before?).
> 
> That was resolved yesterday so I would expect it to show data from last night's pipelines unless there's another issue stopping it from being picked up - we had [JDK11 builds last night](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/) that were [successfully published as nightlies](https://github.com/adoptium/temurin11-binaries/releases/tag/jdk11u-2022-03-02-04-49-beta) so there's still an issue somewhere if they are not being picked up.
> 
> > `===> JDK 11 nightly pipeline publish status: healthy. Last published: 19 day(s) ago`
> 
> That suggests it's still not picking up the data [from the temurin pipelines](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-temurin/) correctly yet and is getting the [last published one](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/) from before the change

I concur. There is still something wrong. Also, why is it reporting it as healthy when it's > 15 days ago and stale threshold is 4 days?

**Comment by sophia-guo** [comment] 2022-03-02 23:10
The new PR  output is 
```
[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/598/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/598/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/598/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/598/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/598/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/598/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/598/console#)[](https://ci.adoptopenjdk.net/view/Tooling/job/nightlyBuildAndTestStats_hotspot/598/console#)[Pipeline] echo
-------------- Nightly pipeline health report ------------------
[Pipeline] echo
===> JDK 8 nightly pipeline publish status: unhealthy. Last published: 15 day(s) ago. Stale threshold: 4 days.
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: adoptium, channel: #build, color: warning, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] echo
===> JDK 11 nightly pipeline publish status: unhealthy. Last published: 19 day(s) ago. Stale threshold: 4 days.
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: adoptium, channel: #build, color: warning, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] echo
===> JDK 17 nightly pipeline publish status: unhealthy. Last published: 19 day(s) ago. Stale threshold: 4 days.
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: adoptium, channel: #build, color: warning, botUser: false, tokenCredentialId: slack-token, notifyCommitters: false, iconEmoji: <empty>, username: <empty>, timestamp: <empty>
[Pipeline] echo
```

**Comment by sophia-guo** [comment] 2022-03-02 23:11
The next step would check why no new data in trss. Should restart TRSS? @sxa

**Comment by sophia-guo** [comment] 2022-03-03 05:10
No data issue opened in https://github.com/adoptium/aqa-test-tools/issues/623

**Comment by sxa** [comment] 2022-03-03 15:55
Suggest @llxia or @Haroon-Khel takes that action (although is that just a guess, or is there something specific that you think will require a restart? The concern is obviously that with an out of space issue there may be files that have got truncated. It's also not currently clear - at least to me - why an out of space issue outside the `/data` file system would have caused the instability we are experiencing)

**Comment by sophia-guo** [comment] 2022-03-03 16:09
Not sure what do you mean by 'truncate' , is it the issue mentioned in https://github.com/adoptium/ci-jenkins-pipelines/issues/254#issuecomment-1054249937? If that is the case maybe reopen #254

**Comment by llxia** [comment] 2022-03-03 16:44
I would also suggest restarting the TRSS services. 
It seems the method of running TRSS changed. I cannot find TRSS log anymore and I do not know how to restart it.

And I think we may have a disk space issue soon:
```
Filesystem      Size  Used Avail Use% Mounted on
udev            7.6G  302M  7.3G   4% /dev
tmpfs           1.6G  816K  1.6G   1% /run
/dev/nvme1n1p1  7.7G  7.6G  148M  99% /
tmpfs           7.6G  828K  7.6G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.6G     0  7.6G   0% /sys/fs/cgroup
/dev/nvme0n1p2  167G  5.5G  153G   4% /data
/dev/loop6       34M   34M     0 100% /snap/amazon-ssm-agent/3552
/dev/loop4       25M   25M     0 100% /snap/amazon-ssm-agent/4046
/dev/loop1      100M  100M     0 100% /snap/core/11993
/dev/loop3       56M   56M     0 100% /snap/core18/2253
/dev/loop5       56M   56M     0 100% /snap/core18/2284
/dev/loop2      111M  111M     0 100% /snap/core/12603
tmpfs           1.6G     0  1.6G   0% /run/user/0
```

**Comment by smlambert** [comment] 2022-03-04 00:21
Reopening this.  If the method for running TRSS has changed, it would be a change driven by the infra team, so needs infra input/assistance.

**Comment by sxa** [comment] 2022-03-04 11:29
> Not sure what do you mean by 'truncate' , is it the issue mentioned in [#254 (comment)](https://github.com/adoptium/ci-jenkins-pipelines/issues/254#issuecomment-1054249937)? If that is the case maybe reopen #254

I am NOT referencing any specific issue. I am saying, as a system administrator, that if the disk space fills up on any machine and an application runs on that file system, there is a risk that files are not correctly written and become corrupted/shortened due to the out of space conditions. In order to understand how likely that we'd need to know if TRSS writes anything to the file system other than in the `/data` directory (since that one was safe and did not fill up). I'm calling it out as a risk that there may be files in that state that will prevent restarts. It may be a non-issue. We could just restart it and see if it comes back, but there is a risk of such a condition and it would need careful watching while it comes back up in order to minimise the risk of downtime.

> If the method for running TRSS has changed, it would be a change driven by the infra team, so needs infra input/assistance.

NOTHING HAS CHANGED on the production server so far.

**Comment by smlambert** [comment] 2022-03-04 13:14
We are in a broken state at the moment.  I am presuming the only option is to restart it.  Someone please correct me if that assumption is incorrect.  I am not sure why the all-caps shouting.  From my read of what Lan shared in a comment above, there have been cores written to disk, so that is something we know is being written to disk.  

/data is not the issue.  The request during community scrum to increase the amount of space (currently 8G?) for where the server is running was denied (can't remember the reason, because it is hard to do?  because of Yeah Nah?)

I would like everyone to keep their eye on the end goal here and work towards a solution that can work for the project.  I would like to be able to use TRSS for next weeks project triage, and in its current state that will not be possible.

**Comment by sxa** [comment] 2022-05-17 17:23
Publish job has now been publishing for a while - closing.

**Closed by sxa** 2022-05-17 17:23 UTC
Labels: testing, hotspot
