### ISSUE TITLE
jdk8 aarch32 JDK doesn't seem to get downloaded to JCK jck_run folder?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/ci-jenkins-pipelines#693] opened 2023-04-27 07:57 UTC
The aqa_test_pipeline doesn't seem to be downloading the JDK ?

**Comment by sophia-guo** [comment] 2023-04-27 16:55
The reason is the build is using v2023.01,  which is incorrect.  @andrew-m-leonard 

 {
    "branch": "v2023.01",
    "remotes": {
        "url": "https://github.com/adoptium/ci-jenkins-pipelines.git"
    }
}

https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk8u/job/jdk8u-release-linux-arm-temurin/3/consoleFull
```
 > git init /home/jenkins/.jenkins/workspace/build-scripts/jobs/release/jobs/jdk8u/jdk8u-release-linux-arm-temurin # timeout=10
Fetching upstream changes from https://github.com/adoptium/ci-jenkins-pipelines.git
 > git --version # timeout=10
 > git --version # 'git version 2.25.1'
 > git fetch --tags --force --progress -- https://github.com/adoptium/ci-jenkins-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/adoptium/ci-jenkins-pipelines.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/adoptium/ci-jenkins-pipelines.git # timeout=10
Fetching upstream changes from https://github.com/adoptium/ci-jenkins-pipelines.git
 > git fetch --tags --force --progress --prune -- https://github.com/adoptium/ci-jenkins-pipelines.git  +refs/pull/*:refs/remotes/origin/pr/* +refs/heads/master:refs/remotes/origin/master +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision 5c8e7342b0fe1db423a3030b849d9f6d5c72efee (refs/remotes/origin/v2023.01)
Commit message: "fix: typo (#594)"
First time build. Skipping changelog.
```

**Comment by sophia-guo** [comment] 2023-04-27 17:09
Close it as it is caused by using the older version.

**Closed by sophia-guo** 2023-04-27 17:09 UTC
Labels: aarch, testing

**Comment by sophia-guo** [comment] 2023-04-27 18:33
See https://adoptium.slack.com/archives/C024CQ8SV7D/p1682615120289689 and https://github.com/adoptium/ci-jenkins-pipelines/issues/694
