### ISSUE TITLE
Ensure regular Build and Test cycle for Solaris platforms

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#115] opened 2021-04-01 17:33 UTC
We have 2 solaris platforms that are being built for jdk8/hotspot:
- [solaris_sparcv9](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot/) 
- [solaris_x86-64](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/)

If we are planning to build and distribute them, we should:
- verify with @AdoptOpenJDK/tsc what the sponsorship with Delphix has committed us to deliver
- confirm this is only for jdk8
- ensure agreed upon platforms are added to the build pipelines
- ensure default testing is enabled and run

**Comment by adamfarley** [comment] 2021-07-02 14:57
@smlambert - Here's a PR to enable pipeline testing on the builds: https://github.com/adoptium/ci-jenkins-pipelines/pull/175

As far as I know, this is all that should be required. What do you think?

**Comment by adamfarley** [comment] 2021-07-02 16:54
The PR mentioned above is merged. Will review the test completion times on Monday before wrapping this up, just to be certain that we have enough machine time. We probably do, based on the [facts we have](https://github.com/adoptium/ci-jenkins-pipelines/pull/175#issuecomment-873099756), but we can't be sure until the weekend runs are complete.

**Comment by adamfarley** [comment] 2021-07-05 16:28
Weekend runs have been assessed.

[Solaris Sparcv9](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot/503/console) - Tests ran as intended. Total runtime = Almost 6 hrs (including a timeout).
Even if we only ever have one machine for this, there's no concern over runtime.

[Solaris x64](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/640/console) - Tests were started as intended, however the lack of "ant" on those machines means none of the test jobs were successful. [Here](https://github.com/adoptium/infrastructure/issues/2254)'s an infrastructure issue to resolve that.

**Comment by sxa** [comment] 2021-07-05 21:13
Infra issue has been resolved therefore closing this

**Closed by sxa** 2021-07-05 21:13 UTC
Labels: enhancement, hotspot, investigate, solaris, sparcv9, testing, x64
