### ISSUE TITLE
Set VENDOR_TEST_DIRS for runSmokeTests

### ISSUE THREAD

**Issue by smlambert** [adoptium/ci-jenkins-pipelines#119] opened 2021-04-08 13:41 UTC
When we use the mechanism to point to non-AQA repositories for test material, we have to tell the test pipeline where to location the test source in the non-AQA repo.

For build and packaging smoke tests, we need to set VENDOR_TEST_DIRS=/test/functional (as done in https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk16u/job/jdk16u-linux-x64-hotspot_SmokeTests/3/, without it set, the job will fail as seen in https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk16u/job/jdk16u-linux-x64-hotspot_SmokeTests/1.

This should be being set by the contents of a JSON file (see https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L144) for jdk16 I am guessing this param is undefined.

**Comment by sophia-guo** [comment] 2021-04-08 14:23
Pipe job configuration has been updated correctly by job https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/build-pipeline-generator/3574/, believe the job was trigger the PR triggered by github hook though I don't have permission to see detail. 
 https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/configure

The problem is build job configuration has not been updated. 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk16u/job/jdk16u-linux-x64-hotspot/configure

This is common to all jdk version.

As adoptium don't generate jobs dynamically. I believe job need to regenerate all build jobs. For example:
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk16u/

**Comment by sophia-guo** [comment] 2021-04-08 14:26
Looks like to regenerate jdk version is the only parameter to set. @M-Davies is that correct? I can give it a try to regenerate jdk8,11, 16 and jdk (pipeline_jobs_generator_jdk)

**Comment by sophia-guo** [comment] 2021-04-08 14:29
This also make me think if  [ pipeline-job  ](https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/build-pipeline-generator) can be parameterized with a boolean : if build job need to be regerated too? According the the PR.

**Comment by sophia-guo** [comment] 2021-04-08 14:31
Or committer comment trigger to regerate necessary build jobs.

**Comment by sophia-guo** [comment] 2021-04-08 14:34
> That when the smoke tests fail, the builds still finish green (passed).

@adamfarley  Eventually smoke tests failed the build job should fail. For now as the workflow has not been smoothy as expected. Smoke tests failure will just disable run-aqa tests. And have the warning message.

**Comment by adamfarley** [comment] 2021-04-08 14:37
> Smoke tests failure will just disable run-aqa tests. And have the warning message.

Thanks for telling me. I will watch out for this behaviour in the future.

**Comment by sophia-guo** [comment] 2021-04-09 18:30
All build jobs have been regerated. https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk16u/
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk8u/
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk11u/
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk/

Jobs' configuration looks fine. Both DEFAULTS_JSON and ADOPT_DEFAULT_JASON set with  `"test_dirs": "/test/functional",`
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk16u/job/jdk16u-linux-x64-hotspot/configure, close it.

**Closed by sophia-guo** 2021-04-09 18:30 UTC
Labels: bug

**Comment by smlambert** [comment] 2021-04-09 19:16
Thanks @sophia-guo !
